version: 2.1
jobs:
  build:
    docker:
      - image: cypress/browsers:chrome67
    working_directory: ~/project
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      # Install dependencies
      - run:
          name: npm update
          command: npm i -g
      - run:
          name: Install Dependencies
          command: npm install --force
      # Run Cypress tests
      - run:
          name: Run Cypress Tests
          command: npm run cypress:run

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
